array_layout = "Block"
chain_indent = "Block"
closure_block_indent_threshold = -1
combine_control_expr = true
control_style = "Rfc"
fn_args_layout = "Visual"
fn_args_paren_newline = false
fn_return_indent = "WithArgs"
fn_single_line = false
generics_indent = "Visual"
reorder_imported_names = true
reorder_imports_in_groups = true
where_density = "CompressedIfEmpty"
